version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "6500:6500"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "50:50"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
